title: inTable

description: >
  JSP Project 2조 삼시n끼 (n > 3) inTable

baseurl: ""

url: "http://sistfers.github.io/intable"

github_username: sistfers

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-slate

markdown: kramdown

kramdown:
  input: GFM

timezone: KR
